### ISSUE TITLE
When I click on Apple Pay, this screen appears for two seconds and then disappears

### ISSUE THREAD

**Issue by abdullah-almasry** [UNICODE-Venture/unicode-moyasar#1]
![WhatsApp Image 2023-03-12 at 6 43 27 PM](https://user-images.githubusercontent.com/66563756/224560227-08c058fc-5b2c-4baf-9acb-06d8c6b120d2.jpeg)

**Comment by mohammadsaif19** [comment]
Go to the moyasar dashboard then go to **settings** then click **Apple Pay - Domains** then click on **Add domain** button add this URL `unicode-moyasar.web.app` and click **Add domain** and then you will see the button called **Validate** tap on it to register and you're done with Apply pay integration.

**Comment by abdullah-almasry** [comment]
نفس المشكله

في الأحد، ١٢ مارس ٢٠٢٣ ٧:٢٣ م Mohammad Saiful Islam Saif <
***@***.***> كتب:

**Comment by mohammadsaif19** [comment]
Please provide an screenshot of moyasar **Apple Pay - Domains** tab under the settings

**Comment by abdullah-almasry** [comment]
ممكن الفيس او الوتساب اكلم حضرتك

في الأحد، ١٢ مارس ٢٠٢٣ ٩:٣٧ م Mohammad Saiful Islam Saif <
***@***.***> كتب:

**Comment by abdullah-almasry** [comment]
في الأحد، ١٢ مارس ٢٠٢٣ ٩:٥٣ م abdullah almasry <
***@***.***> كتب:

**Comment by mohammadsaif19** [comment]
You can contact me through the [Twitter](https://twitter.com/mohammadsaif05) or else check my GitHub profile for more info

**Comment by abdullah-almasry** [comment]
![WhatsApp Image 2023-03-14 at 11 50 39 AM](https://user-images.githubusercontent.com/66563756/224962820-82503d95-f484-4898-b8d5-634777beb51e.jpeg)

the same issue

**Comment by mohammadsaif19** [comment]
Please make sure you're using a real **iOS device** not the **simulator**.

**Comment by abdullah-almasry** [comment]
Yes this from real device

في الثلاثاء، ١٤ مارس ٢٠٢٣ ٩:٤٢ م Mohammad Saiful Islam Saif <
***@***.***> كتب:

**Comment by mohammadsaif19** [comment]
We addressed the bugs in our new release `v1.0.3` please update the version and make sure you use the real device for testing Apple Pay.

**Comment by abdullah-almasry** [comment]
https://user-images.githubusercontent.com/66563756/225370736-00c7ce47-c9b1-4a2c-8457-4da0ce89e156.mp4

I make update the version to v1.0.3  and remove pods and clean project but same issue

**Comment by abdullah-almasry** [comment]
any solution?

**Comment by mohammadsaif19** [comment]
Can you please try with **LIVE token** instead of test token and if it's doesn't solve the issue please provide a screenshot your code snippet

**Comment by abdullah-almasry** [comment]
This is live

في الخميس، ١٦ مارس ٢٠٢٣ ١١:٥١ م Mohammad Saiful Islam Saif <
***@***.***> كتب:

**Comment by mohammadsaif19** [comment]
Make sure you pass the `appName` in English not Arabic and use the live credentials and test the app on real iOS device which supports Apple pay.
